### PR TITLE
Fix network typo

### PR DESCRIPTION
**Pull request by vincentlabonte**
Fix typo in latest release

```
2024-02-09 19:57:06.547 ERROR (MainThread) [homeassistant.setup] Error during setup of component neviweb130
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
result = await task
^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
data = Neviweb130Data(hass_config[DOMAIN])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
self.neviweb130_client = Neviweb130Client(username, password, network, network2)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/neviweb130/__init__.py", line 199, in __init__
self.__get_network()
File "/config/custom_components/neviweb130/__init__.py", line 252, in __get_network
self._occupancyMode = network[0]["mode"]
^^^^^^^
UnboundLocalError: cannot access local variable 'network' where it is not associated with a value
```

### CODE REVIEW

**Comment by F-Forget** [comment]
Thank you, this fixed my issue 🙂!

**Review by F-Forget — APPROVED** [review]
This fixes the issue in HA.

**Comment by claudegel** [comment]
Thank you I'll set a new release tonight as I have 2-3 things to add

**Comment by claudegel** [comment]
released in 2.6.4

**Pull request merged**
