### PR TITLE
Add support of multi-residential valves

### PR DESCRIPTION
**Pull request by dr1rrb**
Add model identifiers of multi-residential valves (https://www.sinopetech.com/us/sedna/multi-residential-condominiums/sedna-mesh-technical-specifications/)

### CODE REVIEW

**Comment by claudegel** [comment]
Where did you get ACT4220WF-M, in the doc from Sinopé those valves are called VA4221WF-M and VA4220WF-M.
Also do you know if there are specific attributes added in Neviweb for those valves. If yes I think it is better to create another group like IMPLEMENTED_WIFI_MESH_VALVE_MODEL and IMPLEMENTED_ZB_MESH_VALVE_MODEL. This way it will be easier to add specific attributes received from Neviweb

**Comment by dr1rrb** [comment]
@claudegel 

Yes the doc states that it should be VA422XWF-M and VA422XZB, but the reported device in the logs are actually ACT4220WF-M and ACT4220ZB-M. I also validated on the valve itself: it's those model numbers that are engraved on the side.

For the specific attributes, I didn't saw anyone, but here are logs I got:
```
2022-10-06 17:24:16.251 DEBUG (SyncWorker_6) [custom_components.neviweb130] Received signature data: {'signature': {'model': 3155, 'modelCfg': 0, 'softBuildCfg': 3, 'softVersion': {'major': 2, 'middle': 5, 'minor': 3}, 'hardRev': 0, 'protocol': 'sinopcom'}}
2022-10-06 17:24:16.315 DEBUG (SyncWorker_6) [custom_components.neviweb130] Received signature data: {'signature': {'model': 31532, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'major': 0, 'middle': 1, 'minor': 2}, 'hardRev': 0, 'protocol': 'sinopcom'}}
```

And the "gateway data":
```
[{
	'id': ***,
	'identifier': '***',
	'name': 'Actuateur Princ',
	'family': '3155',
	'signature': {
		'model': 3155,
		'modelCfg': 0,
		'softBuildCfg': 3,
		'softVersion': {
			'major': 2,
			'middle': 5,
			'minor': 3
		},
		'hardRev': 0
	},
	'location$id': ***,
	'parentDevice$id': ***,
	'group$id': ***,
	'orderIdx': 0,
	'sku': 'ACT4220WF-M',
	'vendor': 'Sinopé',
	'url_en': None,
	'url_fr': None
}, {
	'id': ***,
	'identifier': '***',
	'name': 'Actuateur Secon',
	'family': '3153-M-VA',
	'signature': {
		'model': 31532,
		'modelCfg': 0,
		'softBuildCfg': 0,
		'softVersion': {
			'major': 0,
			'middle': 1,
			'minor': 2
		},
		'hardRev': 0
	},
	'location$id': ***,
	'parentDevice$id': ***,
	'group$id': ***,
	'orderIdx': 0,
	'sku': 'ACT4220ZB-M',
	'vendor': 'Sinopé',
	'url_en': None,
	'url_fr': None
}]
```

**Comment by dr1rrb** [comment]
F12 :)

**Comment by claudegel** [comment]
So open Neviweb.com. select your ACT4220WF-M and open the console to look at the trafic for this valve. You should see some line like GET https://neviweb.com/api/device/xxx

see the picture below
neviweb_debug

**Comment by claudegel** [comment]
I need all the attributes listed in the response to see if there are some specific for the mesh valves

**Comment by claudegel** [comment]
Yes, do you have the same data for the other valve ACT4220ZB-M ?

**Comment by dr1rrb** [comment]
Not exactly for the second valve the request is

`https://neviweb.com/api/device/***/attribute?attributes=onOff,batteryStatus,batteryVoltage,stm8Error,waterLeakStatus,flowMeterMeasurementConfig`

and the response: 
```
{
	"onOff": "on",
	"batteryStatus": "ok",
	"batteryVoltage": 7,
	"stm8Error": {
		"motorJam": false,
		"motorPosition": false,
		"motorLimit": false
	},
	"waterLeakStatus": "flowMeter",
	"flowMeterMeasurementConfig": {
		"multiplier": 0,
		"offset": 0,
		"divisor": 1
	}
}
```

Also for the main valve (the wifi one) I noticed that each time I go to it, I get the requets/response I sent your few minutes ago, but also a second request with only the `onOff` attribute: `https://neviweb.com/api/device/***/attribute?attributes=onOff` ... most probably a bug in their web app, but just to let you know.

**Comment by dr1rrb** [comment]
> You say: Not sure however where does the attributes list is coming from those attributes are what the neviweb.com website is asking to the Neviweb server to update itself. This is what we use to update HA devices status

Yes my question was to understand how the neviweb web app is building the query. For instance why it is requesting the `motorPosition` for the main valve but not for the second one. I would assume that can found somewhere a list of all _attributes_  that are supported by the device.

**Comment by claudegel** [comment]
The wifi valve is using a private protocole from Sinopé. The zigbee valve must comply with the public zigbee protocole where less parameters are supported now

**Comment by claudegel** [comment]
Let me check if the attributes you sent are the same used for the sedna wifi and zigbee 2e gen. If yes we will merge your patch. If there are some difference I'll add  what is missing to have a more complete patch. As I was working in the addition of the flow monitor I'll first merge your patch to the flow-sensor branch. This way I'll be able to publish a new release that cover all.

I will also send a PR to ZHA to add support for ACT4220ZB-M and ACT4221ZB-M so they are recognised by ZHA in HA

**Comment by dr1rrb** [comment]
FYI, I found the answer to my question: all devices and their supported capabilities / attributes are listed in a `main.js` file (https://neviweb.com/main.1057703d18d2d346.js) that is loaded when you open the first page of Neviweb.

But this is not a simple json mapping that could be used to generate all devices at once, it's lot of classes, one for each device type. For instance, if we search for the WL4200 sensor, we found 3 matching classes (probably one per hardware revisions):
```js
class je extends t.A {
	constructor(Ze) {
		super(),
		this.thumbnailAttributes = ["waterLeakStatus", "batteryStatus", "roomTemperatureAlarmStatus", "batteryVoltage", "batteryType"],
		this.actionAttributes = ["batteryStatus", "waterLeakStatus", "roomTemperature", "roomTemperatureAlarmStatus", "batteryVoltage", "batteryType"],
		this.settingsAttributes = ["signature", "cfgValveClosure", "batteryType"],
		this.hasSMSAlarm = !0,
		this.isValveChild = !0,
		this.childThumbnailAttribute = "waterLeakStatus";
		for (const Te in Ze)
			this[Te] = Ze[Te];
		this.initAttributesArrays(),
		this.setInfo("SondeValveComponent", "DeviceActionSondeComponent", "DeviceSettingSondeComponent", "zigbee", "Sensor", "detecteur", 13, "WL4200", !1, !1, !1, !1)
	}
}
class De extends t.A {
	constructor(Ze) {
		super(),
		this.thumbnailAttributes = ["waterLeakStatus", "batteryStatus", "roomTemperature", "batteryVoltage", "batteryType", "roomTemperatureAlarmStatus"],
		this.actionAttributes = ["waterLeakStatus", "batteryStatus", "roomTemperature", "batteryVoltage", "batteryType", "roomTemperatureAlarmStatus"],
		this.settingsAttributes = ["signature", "batteryType", "alertLowBatt", "alertWaterLeak", "alertLowTemp", "rssi"],
		this.childThumbnailAttribute = "waterLeakStatus";
		for (const Te in Ze)
			this[Te] = Ze[Te];
		this.initAttributesArrays(),
		this.setInfo("SondeValveComponent", "DeviceActionSondeComponent", "DeviceSettingSondeComponent", "zigbee", "Sensor", "detecteur", 8, "WL4200", !0, !1, !1, !1)
	}
}
class tt extends t.A {
	constructor(Ze) {
		super(),
		this.thumbnailAttributes = ["waterLeakStatus", "batteryStatus", "roomTemperatureAlarmStatus", "batteryVoltage", "batteryType"],
		this.actionAttributes = ["batteryStatus", "waterLeakStatus", "roomTemperature", "roomTemperatureAlarmStatus", "batteryVoltage", "batteryType"],
		this.settingsAttributes = ["signature", "cfgValveClosure", "batteryType"],
		this.hasSMSAlarm = !0,
		this.isValveChild = !0,
		this.childThumbnailAttribute = "waterLeakStatus";
		for (const Te in Ze)
			this[Te] = Ze[Te];
		this.initAttributesArrays(),
		this.setInfo("SondeValveComponent", "DeviceActionSondeComponent", "DeviceSettingSondeComponent", "zigbee", "Sensor", "detecteur", 13, "WL4200", !1, !1, !1, !1)
	}
}```

And this is how the query to get attributes are built by the neviweb app. For instance the request made for my WL4200 sensors is `https://neviweb.com/api/device/***/attribute?attributes=batteryStatus,waterLeakStatus,roomTemperature,roomTemperatureAlarmStatus,batteryVoltage,batteryType`. We can see that the requested attributes are those defined in the `actionAttributes`.

Then it also means that we can discover few extra attributes, for instance if I request `https://neviweb.com/api/device/***/attribute?attributes=cfgValveClosure,alertLowTemp,alertWaterLeak` for my sensors I get:

```
{"cfgValveClosure":"on","alertLowTemp":true,"alertWaterLeak":true}
```

Note: For my sensors, there is only the `cfgValveClosure` that is not reported by HA.

**Comment by claudegel** [comment]
very interesting. with that I can improve a lot in HA. 
When I compare your valve attributes with my old valve attribute, first gen, I can see that there are many difference between the first and second generation. So I'll add support for your ACT valve by creating new IMPLEMENTED_WIFI_MESH_VALVE_MODEL and IMPLEMENTED_ZB_MESH_VALVE_MODEL to get all specific atributes for those mesh valves. 
I should be able to have a working branch by tomorrow.

for cfgValveClosure this attribute is only available if your leak sensor is connected directly to the valve, If it is connected to the GT130 it is not used by Neviweb

**Comment by claudegel** [comment]
How do you get the main.js file all ordered like what you show above

**Comment by claudegel** [comment]
My main.1057703d18d2d346.js file is a little different then the one you have
For example I don't have class je extends t.A {
Instead I have class Ke extends t.A {
Is it possible that this file is generated based on what you have in your Neviweb ?
Is so can you send me a copy of yours

**Comment by dr1rrb** [comment]
> Is it possible that this file is generated based on what you have in your Neviweb ? Is so can you send me a copy of yours

Yes it makes sense that the file is generated per account depending of the devices you own ... at least to avoid to transfer too much stuff as they are their range of products becomes larger. Mine is:  [main.js.txt](https://github.com/claudegel/sinope-130/files/9735981/main.js.txt)

> How do you get the main.js file all ordered like what you show above

I opened it in notepad++ and used the JSTool plugin to format it (plugin / JSTool / JSFormat). Even if it's not json, it works well enough to make the file readable. Be aware that it's a quite heavy task to process the whole file!

**Comment by claudegel** [comment]
Thank you, I was able to convert mine with https://beautifier.io/
There are lot of stuff in that file. will allow me to complete support for the valve et leak sensor and check all other devices.

**Comment by claudegel** [comment]
Hi it's ready to test. please load branch https://github.com/claudegel/sinope-130/tree/flow-sensor
only file sensor.py, switch.py and const.py have changed.
Let me know

**Comment by dr1rrb** [comment]
The device are loading, but the state of the switch is not updated properly when not directly switch from HA.

Looking at the code, I think it's because the `self._onOff` is not being updated.

Copying the values from the standard wifi and zigbee valves does fix the issue : https://github.com/claudegel/sinope-130/commit/c947035c9de325d6ed6f5b19ebe80a97bf89ea41

**Comment by claudegel** [comment]
Thanks I've added your patch
Tomorrow I'll add support for the new load control for water heater RM3500ZB.
I've found data in the main file

**Comment by dr1rrb** [comment]
Thanks for your work on this project, it was really easy to integrate all my devices in HA, it's really great 😍

**Comment by claudegel** [comment]
I've also added support for RM3500ZB which is coming this fall and will be used for Hilo project.
Thank you for your help I'm gonna publish a new release for those new supported devices today.

**Comment by claudegel** [comment]
In your Neviweb/firefox console do you see this line for your wifi or zigbee valve
https://neviweb.com/api/device/258170/alert
If yes I'll update switch.py to catch that alert.
I have it for my sedna connected to the GT130 and this allow to catch alert message for low battery and low temperature

**Comment by dr1rrb** [comment]
> In your Neviweb/firefox console do you see this line for your wifi or zigbee valve https://neviweb.com/api/device/258170/alert If yes I'll update switch.py to catch that alert. I have it for my sedna connected to the GT130 and this allow to catch alert message for low battery and low temperature

No, I get several calls to `api/device/{deviceId}/attribute` for the valve itself and one for each device that can turn off that valve (which appears on the same page).

Is it possible that this call is made only when there is a pending alert? (i.e. should I put a sensor in the water to trigger an alert?)

Also, sure what's in the `alert` API, but I noticed that I also have recurring call to `api/notifications?account$id={accountId}`. I would assume that we should be able to get alert info here? Here is the result of that call:
```json
{
	"notifications": [],
	"totalAlerts": 0,
	"totalMaintenance": 0,
	"totalCommunication": 0,
	"totalUnread": 0
}
```

**Comment by claudegel** [comment]
With the sedna zigbee valve the call api/device/{deviceId}/alert is done to show to property for that valve:
alertLowBatt and alertLowTemp, to show if those alert are activated on the valve.
On Neviweb they show up only if you open the valve card then open the config section.
This is helpfull to know if those two alert are activated for the valve. I don't know if it is the same for the mesh valve.
As for api/notifications?account$id={accountId} I'll have a look on my side. maybe it could be use to monitor the complete system for any alert or bug

**Pull request closed without merging**
