### PR TITLE
Use JSON parameter for initialization login request

### LINKED ISSUE #255: Restart problem
How can I correct this situation? For your information, I have just updated HA's operating system.

**Here's a copy of the log:**

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 4:47:58 PM (1 occurrences)
Last logged: 4:47:58 PM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 198, in __init__
    self.__post_login_page()
  File "/config/custom_components/neviweb130/__init__.py", line 221, in __post_login_page
    raise PyNeviweb130Error("Cannot log in")
custom_components.neviweb130.PyNeviweb130Error: Cannot log in

### PR DESCRIPTION
**Pull request by lamungu**
### Description

Fixed authentication issue preventing the API to connect to Neviweb. Fixes #255 

### Changes Made
- Use `json` parameter for the login request at initialization

### CODE REVIEW

**Comment by lamungu** [comment]
@claudegel

**Comment by marcolivierarsenault** [comment]
This PR, fixed it for me

**Comment by Drizztfire** [comment]
Also worked for me
Thanks !

**Comment by BeyondCurious** [comment]
How can I update my system with this fix? I too am experiencing this issue.

**Comment by wiredmax** [comment]
Thanks for the fix!

**Comment by jbenard2000** [comment]
Hi,
Someone can help me...
I don't know how to make this change.
Anyone can explain to me in detail?
Thanks!

**Review by fransixles — APPROVED** [review]
the change fixes #255

**Comment by claudegel** [comment]
Good to go. will push a new release tonight

**Pull request merged**
